source "https://rubygems.org"

ruby "3.4.1"

gem 'roda'
gem 'aws-sdk-s3'   # most common (S3 usage)
gem 'puma'
gem 'oj', platforms: :ruby
gem 'rack'
gem 'rake'
gem 'rackup'
gem 'csv'
gem 'activesupport', require: 'active_support/all'
gem 'jwt'
gem 'fiddle'
gem 'sequel'
gem 'pg'
gem 'sequel_pg', platform: 'ruby', require: false
gem 'bcrypt'
gem 'json_schemer'

gem 'nokogiri'
gem 'rack-cors', :require => 'rack/cors'
gem 'sequel_enum'
gem 'newrelic_rpm'

gem 'ferrum'
gem 'stripe'
gem 'httpx'
gem 'parallel'
gem "attr_encrypted"
gem 'dotenv'
gem 'rufus-scheduler'
gem 'tzinfo-data'

gem 'mail'


group :development do
  gem 'listen'
  gem 'byebug', platforms: 'ruby'
  gem 'racksh'
  # gem 'thor'
  # gem 'sqlite3'
end

# bundle lock --add-platform x86_64-linux